### ISSUE TITLE
Introduce Bizual 2nd model: Monitor inventory direct from Warehouse

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Beelina#173]
Today, inventory distribution is coming from Warehouse  to Panel (Sales agent account). Stocks is being withdrawn from Warehouse to Panel, this means that sales agents have their autonomous inventory in which they distribute to their customers. 

Now, our goal is to make Bizual to be more flexible in a way that it can support a process where distribution is being monitored directly from warehouse, there is no withdrawal for this type of process. When registering orders. it will directly the stocks from warehouse. 

**TODO:**
Consider the following pages/process when implementing this new mode:
- [x] Product list page
- [x] Product Cart page
- [x] Validation stocks when registering order
- [x] Product Stock Audits
- [x] Transfer Stocks Feature
- [x] Ending Inventory Report
- [x] Product Withdrawal Report

There could be more pages. Please take note of that.

**Comment by RoiJS** [comment]
## Product List Page

### Product Catalogue
For manager accounts, products can still be seen based on the selected sales agent. _Stocks are based on the warehouse but not the price_. Prices still varies on the sales agent. 

For Sales agents, stocks shown are based on warehouse but prices are shown based on what have been assigned to them by the managers.

### Warehouse Products
Basically, nothing has changed here, stocks and prices are still based on the warehouse.

## Product Cart page
When setting up orders, checking of stocks is based on the warehouse but prices is based on the assigned price on the agent.

## Validation stocks when registering order
When confirming orders, product stocks will be checked against warehouse stocks.

## Product Stock Audits
Tracking of stock audits will be based on the activities managing product stocks directly from warehouse (ei. Order from Supplier, Transfer of stocks, etc) and also the stocks set on the confirmed orders.

## Transfer Stocks Feature
Warehouse can also use transfer of stocks feature. This way we can transfer/convert items from one unit to another. Activities on transferring stocks can also be seen from product stock audit page.

## Ending Inventory Report
This report is now available on all types of user accounts regardless of the business model but only differs on the data that will be generated.

### Warehouse-Panel-Monitoring Business Model
For sales agents, this will extract the ending report based on the panel inventory, based on stocks and prices on their panel.
For managers, they can choose from which sales agent they would like to generate report from. Stocks and prices is based on the selected sales agent account.
For administrators, this works the same with manager accounts.

### Warehouse-Monitoring Business Model
For sales agents, ending inventory will be based on the warehouse but the prices used for calculation will be based on the assigned prices on the sales agent.
For managers, ending inventory will be based on the warehouse and the prices used for calculation will be based on the warehouse prices.
For administrators, this works the same with manager accounts.

## Product Withdrawal Report
This report is not available on the 2nd model since monitoring is directly from the warehouse. There is no concept of withdrawal here.

**Comment by RoiJS** [comment]
New updates are now merged to Development branch. Moving this ticket to close now.
