### ISSUE TITLE
Introduce "Mark As Paid" option on order registration

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Beelina#221]
In ticket #139, we have removed the "Mark as Paid" feature and replace it with the idea of making the payment method determine whether the order is Paid or Not. 

Now, we will be sort of re-introducing this Mark as Paid feature and make the mode of payment not tied with the Order status.

**TODO:**
- [x] Study the previous commit linked with #139 and see which parts can be re-introduce
- [x] Make sure to add this Mark as Paid on Order transaction page as well
- [x] When marking order transaction as "Confirm", present the user the option to automatically mark the order transaction as paid as well. 
- [x] Test and verify

**Comment by RoiJS** [comment]
**Done:** Mark as Paid button is now available again. Order status (Paid or Not) is no longer determined based on the Mode of payment. 

There is a way for the user to automatically mark the order as paid when setting the order to confirm.
![Image](https://github.com/RoiJS/Beelina/assets/17162501/0bc909c4-d498-429d-8fb8-457736c6832b)

User can also now set the order as paid or unpaid anytime unlike before introducing ticket #139 where once the user mark it as paid, the action is not reversible.
