### ISSUE TITLE
Introduce send invoice via email

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Beelina#244]
As a sales agent, I would like to have an option to send order receipt as PDF via email. There must be a setting where to set the email address where to send the order receipt. The order receipt template must be the same with the template use when printing order receipt via the order transactions page on admin accounts so find an efficient way to re-used the same logic/code. The must be in a PDF format  as well.

#### TODO:
- [x] Introduce email address setting. It would be nice if we start developing a **Settings** page for admin account and place the setting there.
- [x] Introduce a configuration field on user level to allow use to send order receipt via email.
- [x] Introduce an option to send order receipt as email in transaction details page.
- [x] Trigger the sending email when confirming order.
- [x] Test and verify
