### ISSUE TITLE
Create Ending Inventory Per Product Report

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Beelina#45]
We will be introducing a new type of report. The user would like to see the beginning and ending stocks for each product per sales agent account for a given date. 

Below is the format that we will be using for the new report.

[EndingInventoryPerProductReport_Template.xlsx](https://github.com/RoiJS/Beelina/files/13360830/EndingInventoryPerProductReport_Template.xlsx)

#### Todo:
- [x] Introduced new report data on tables **Reports** and **ReportControlsRelations**
- [x] Introduced new Store procedure
- [x] Introduced new Report Class in C#
