### ISSUE TITLE
Create Sale Per Customer Report

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Beelina#46]
We will be introducing a new type of report. The user would like to see the sales per customer/store per sales agent account for a given date.

Below is the format that we will be using for the new report.

[SalesPerCustomerReport_Template.xlsx](https://github.com/RoiJS/Beelina/files/13360886/SalesPerCustomerReport_Template.xlsx)

#### Todo:
- [x] Introduced new report data on tables **Reports** and **ReportControlsRelations**
- [x] Introduced new Store procedure
- [x] Introduced new Report Class in C#
