### ISSUE TITLE
Support Beelina offline mode

### ISSUE THREAD

**Issue by RoiJS** [RoiJS/Beelina#61]
The goal here is to add support for offline mode in Bizual. The idea here is for the agent to be able to at least record orders as draft then later on they can confirm the orders once connection is restored. This gives Bizual more value as productivity tool for sales agents.

In order for the app to handle offline orders, we must make the following entities available when connection is not available:
- Customer Accounts
- Customers
- Products
- Draft Transactions

We must implement sort of local database where to store these information.
We can make use of [IndexedDb ](https://medium.com/@zeeshankhan8838/angular-and-indexeddb-a-perfect-pair-for-progressive-web-apps-315a39f49) for this use case. 

Here is a great tutorial for that https://sukeshk.medium.com/how-to-use-ngx-indexed-db-in-angular-17-an-efficient-data-persistence-solution-e930558cbe57.

### TODO:
- [x] Create angular service for the local db
- [x] Decide when to store/sync these entities on local db
- [x] Modify the services that communicates with the backend entities to switch between server or local storage when connection is available or not.
- [x] For Draft orders, we will not keep a local copies of the orders from the server. We will only keep new draft orders added during offline then as soon as the connection is available we will save these orders on the server.
- [x] Test and verify
